### ISSUE TITLE
Capacitor 5

### ISSUE THREAD

**Issue by webmasterab** [jofr/capacitor-media-session#12]
Is there any prospect of the development towards Capacitor 5?

Or what can we do to help with this.

**Comment by gondp** [comment]
How can we make it compatible Capacitor 5?

**Comment by webmasterab** [comment]
> How can we make it compatible Capacitor 5?

There is a plugin that can handle that as I read it, but I'm not very familiar with it yet.

https://capacitorjs.com/docs/updating/plugins/5-0

Will see if I can copy my environment to a test environment to give this a try.
However, I have to figure out how to get it into a pull request.

**Comment by jofr** [comment]
The plugin has been updated to Capacitor 5 (3.x versions of this plugin are for Capacitor 5), so I'm closing this now.
