### ISSUE TITLE
Audio cannot be controlled using headset controls

### ISSUE THREAD

**Issue by simonoskamagdalena** [jofr/capacitor-media-session#17]
Hi, I am working on an Ionic application using Angular and Capacitor 5.3.0 and it seems like I cannot play/pause the audio when my  phone is connected to bluetooth headset. Can you please check?
Edit: I am using Redmi buds 3 lite,  Android version 13, Ionic 7 and Capacitor 5. Also it is worth mentioning, that the headset controls work well with Spotify

**Comment by simonoskamagdalena** [comment]
Hi, any progress on this issue or does anyone have any suggestion on how to solve this problem? The controls from bluetooth devices do not work.

**Comment by mikmikmik** [comment]
Same here, only works on iOs.

**Comment by mikmikmik** [comment]
I managed to make it work for Android and iOs by changing in MediaSessionService.java ACTION_PLAY_PAUSE to ACTION_PLAY and ACTION_PAUSE accordingly for both play and pause playbackStateActions and notificationActions
Are there some devices using the play/pause instead? Maybe register both?

**Comment by simonoskamagdalena** [comment]
Thank you @mikmikmik, you are a life saver. This solution worked for me
