### ISSUE TITLE
Update to Capacitor 6.0

### ISSUE THREAD

**Issue by Christoffyw** [jofr/capacitor-media-session#26]
Pretty self explanatory

**Comment by Christoffyw** [comment]
I dropped a PR that should resolve this. Unfortunately it hasn't been tested.

**Comment by Christoffyw** [comment]
Just tested it, and it works.

**Comment by bonomite** [comment]
Thanks @Christoffyw This is the only plug in holding back my v6 upgrade. I hope this gets resolved soon.

**Comment by caf-3** [comment]
I need this into my app :( :(
My app has a Music Player in it and it doesn't make sense to play Music without controls.

**Comment by caf-3** [comment]
If you can guide me, I want to contribute for this project, I'm in love with capacitor and if there is something you need help (in terms of coding 😅). And I don't know Java nor Swift

**Comment by giovannigarifo** [comment]
@caf-3 You can clone the repository and upgrade the project to Capacitor 6.  This in my fork, as an example: [Capacitor Media Session Fork](https://github.com/column-app/capacitor-media-session). Then, point the dependency in your `package.json` to the local path where you cloned the project. For example, if you cloned it in the parent folder of your project, you would add:

```json
"@jofr/capacitor-media-session": "file:../capacitor-media-session"
```

This is a temporary solution while we wait for the merge of the existing pull request: [Pull Request #27](https://github.com/jofr/capacitor-media-session/pull/27).

**Comment by webmasterab** [comment]
@jofr Is it possible to update the plugin to capacitor 6.0.
We need to update the app to capacitor 6.0 in order to write to API 34, which is mandatory as of August 31, 2024 to keep the app in Google Play.

**Comment by webmasterab** [comment]
@giovannigarifo  how can I clone this?
I have no idea what to do and I really want to update to capacitor 6.0.
Can you explain what I need to do?

**Comment by Heshyo** [comment]
@Christoffyw Can you close this issue as your PR #27 has been merged.
