### ISSUE TITLE
setMetadata() promise does not resolve on android

### ISSUE THREAD

**Issue by mariusbolik** [jofr/capacitor-media-session#5]
Hello,

first of all, thank you for this very helpful plugin. I tried all possible solutions to show the media controls on android and I can clearly say, that this plugin is the best solution!

I found one little issue. For me, the `setMetadata()` doesn't resolve.

```ts
await MediaSession.setMetadata(metadata);
// code after the call will not be executed
```
Could you check this please?

---

And could you tell me what's the best order to call the functions? Is it like this?
1. `setMetadata()`
2. `setPlaybackState()`
3. `setPositionState()`
4. `setActionHandler()`
Can it cause problems if I call the functions in a wrong order?

Regards,
Marius

**Comment by mariusbolik** [comment]
I don't know what I am doing wrong. Sometimes `setMetadata()` does not resolve and sometimes `setPlaybackState()` does not resolve. Seams like it depends on the order I'm calling the functions.

**Comment by jofr** [comment]
Hi, so the order in which those functions are called should not be relevant. If it is then that seems to be a bug, I'll have to look into this.

**Comment by jofr** [comment]
Ok, so I didn't get around to this earlier over the holidays but I also can't really reproduce this now. Do you happen to have some example code producing this error? That would help a lot in trying to figure out what's going on :relaxed:

**Comment by Amoyens1s** [comment]
i also meet this on MIUI, setMetadata is always pending
