### ISSUE TITLE
The notifications on Android remain when I stop the media

### ISSUE THREAD

**Issue by webmasterab** [jofr/capacitor-media-session#9]
How can I hide the lock screen notification in Android when I stop the media?

If I pause the media, he'll go away.

Do I have to do something here with the updatePlaybackState().

I've tried everything but I can't figure it out

**Comment by AzielCF** [comment]
You can do the following:

```
MediaSession.setActionHandler({ action: 'stop' }, () => {
  MediaSession.setPlaybackState({ playbackState: 'none' })
})
```

**Comment by AzielCF** [comment]
> ¿Cómo puedo ocultar la notificación de la pantalla de bloqueo en Android cuando detengo los medios?
> 
> Si hago una pausa en los medios, se irá.
> 
> ¿Tengo que hacer algo aquí con updatePlaybackState().
> 
> Lo he intentado todo, pero no puedo entenderlo

You can do the following:

```
MediaSession.setActionHandler({ action: 'stop' }, () => {
  MediaSession.setPlaybackState({ playbackState: 'none' })
})
```
